version: '3.8'

services:
  prod:
    container_name: match-marker
    image: match-marker-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/app
    restart: always
networks:
  nesjs-network:
