version: '3.8'

services:
  # app:
  #   container_name: match_marker_dev
  #   image: match-marker-dev:1.0.0
  #   build:
  #     context: .
  #     target: development
  #     dockerfile: ./Dockerfile
  #   # command: npm run start:debug
  #   ports:
  #     - 3001:3001
  #     - 9229:9229
  #   networks:
  #     - nestjs-network
  #   volumes:
  #     - .:/usr/app
  #     - /usr/app/node_modules
  #   restart: unless-stopped
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: rtb
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - nestjs-network
    volumes:
      - postgres-database:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  nestjs-network:
volumes:
  postgres-database:
